### ISSUE TITLE
`rememberable` module not working

### ISSUE THREAD

**Issue by kevinansfield** [heartsentwined/ember-auth#48]
I have the rememberable module set up in my `auth.coffee` and my server is responding with the correct `remember_token` during sign in but no cookie gets set.

Here is my auth config:

``` coffeescript
App.Auth = Ember.Auth.create

  tokenKey: 'auth_token'
  tokenIdKey: 'user_id'
  userModel: 'App.User'

  signInEndPoint: '/users/sign_in'
  signOutEndPoint: '/users/sign_out'

  modules: [
    'emberData',
    'rememberable',
    'urlAuthenticatable',
    'authRedirectable',
    'actionRedirectable'
  ]

  rememberable:
    tokenKey: 'remember_token'
    period: 14 # days

  urlAuthenticatable:
    paramsKey: 'auth'

  authRedirectable:
    route: 'home.sign_in'

  actionRedirectable:
    signOutRoute: 'home'
    signInRoute: 'newsfeed'
    signInSmart: true
    signInBlacklist: [
      'home',
      'home.sign_in',
      'home.confirmation_required',
      'sign_out'
    ]

```

**Comment by heartsentwined** [comment]
@kevinansfield I'll copy your setup and try to reproduce it, because I just took a quick look at my sandbox and it's working fine
![screenshot from 2013-05-02 23 45 24](https://f.cloud.github.com/assets/2252978/454759/6881c3bc-b33f-11e2-9ada-76053ce33985.png)

**Comment by kevinansfield** [comment]
I've just checked in Chrome and the cookie is set there but after refreshing the page or manually going to a different page via the URL it doesn't recognise me as being logged in.

I'll restart Safari and check again for the cookie there.

**Comment by kevinansfield** [comment]
Ignore the missing cookie problem, it appears that was due to Safari's inspector not actually updating it's cookies display.

The problem with not being automatically signed in when the remember cookie is present is still there.

**Comment by heartsentwined** [comment]
Working on it.

**Comment by heartsentwined** [comment]
Re: the inspector. This has tripped me too, I don't have Safari, but I got a similar problem in Chromium.

There is a refresh button in the inspector
![before](https://f.cloud.github.com/assets/2252978/454914/01c109e0-b343-11e2-92bb-bc0385b3b87d.png)

After clicking it
![after](https://f.cloud.github.com/assets/2252978/454916/0754aca4-b343-11e2-9a26-c22d148900f9.png)

**Comment by kevinansfield** [comment]
Awesome, thanks for the tip, will remember that when I'm in Chrome. Unfortunately Safari is still lacking on the Inspector front and hasn't implemented that feature yet.

**Comment by joscas** [comment]
I also have this issue. I've noticed that `rememberable` works until I start to add other modules. The problem must be due to interference with `authRedirectable`, `actionRedirectable` or `urlAuthenticatable`

**Comment by joscas** [comment]
I think it's `urlAuthenticatable` that breaks it.

**Comment by heartsentwined** [comment]
Fixed in `v6.0.1`.

**Comment by joscas** [comment]
After upgrade I'm still getting the same problem. `urlAuthenticatable` overrides `rememberable`

**Comment by kevinansfield** [comment]
Same here unfortunately

**Comment by heartsentwined** [comment]
@joscas and @kevinansfield I cannot reproduce your observation. I put a couple of `console.log()` statements to verify method call orders, and I duplicated all the [settings](https://github.com/joscas/base_app/blob/ember-auth5/app/assets/javascripts/auth.js) over at [joscas/base_app](https://github.com/joscas/base_app) exactly. Here is what I got:

Trial 1: (your app's setting)

``` javascript
  modules: ['emberData',
            'rememberable',
            'authRedirectable',
            'actionRedirectable',
            'urlAuthenticatable'
            ],
```

Result 
![rememberable-first](https://f.cloud.github.com/assets/2252978/455460/31ecf9d0-b352-11e2-90a6-e3223365e0ec.png)

Trial 2: (swapped positions of `rememberable` and `urlAuthenticatable`)

``` javascript
  modules: ['emberData',
            'urlAuthenticatable',
            'authRedirectable',
            'actionRedirectable',
            'rememberable'
            ],
```

Result
![url-authenticatable-first](https://f.cloud.github.com/assets/2252978/455465/6d7c8c54-b352-11e2-9742-b2222edd4216.png)

I have a template snippet that displays whether I am signed in or not, and this one is working fine too. Manually checking the cookies yield no errors.

I have also tried uninstalling the gem, pulling a fresh version from `bundle update`, `rake assets:clean` to clear assets, restarting server; all working as expected.

**Comment by joscas** [comment]
My test works as follows: First I load with remember me. Then I reload the page. If I have `urlAuthenticatable` in my Auth.conf it doesn't load the model:

``` javascript
BaseApp.Auth.get('userId')
null
BaseApp.Auth.get('authToken')
null
BaseApp.Auth.get('user')
null
```

Then if I deactivate the module and I reload, I get the user loaded and an auth_token

**Comment by heartsentwined** [comment]
Thanks for the information; I tried your tests, and they are still working fine in my sandbox. Perhaps related to some other config in the app? I'll clone your repo again and test it.

**Comment by joscas** [comment]
rspec tests are passing because they relate to rails. Cucumber tests pass because the `urlAuthenticatable` module is commented out.

The auth.js file in ember-auth5 branch has to be modified to reproduce the problem: https://github.com/joscas/base_app/blob/ember-auth5/app/assets/javascripts/auth.js

Uncomment and run `rake cucumber`

**Comment by heartsentwined** [comment]
okay

**Comment by heartsentwined** [comment]
@joscas I still have no idea what went wrong at your end.

I cloned your repo, checked out `ember-auth5` branch, `bundle install`, `rake db:setup`, and I did a manual browser testing in order to inspect the console.

# urlAuthenticatable on

## Test 1
1. (Manually cleared all local cookies.)
2. Start at http://localhost:3000/#/home
3. Click Sign In. Now at http://localhost:3000/#/sign_in
4. `admin@example.com` + `12345678` + remember me `on`, click Sign In
5. Check cookies. `ember-auth-rememberable` is there.
6. Console test

```
[BaseApp.Auth.get('authToken'), BaseApp.Auth.get('userId'), BaseApp.Auth.get('user').get('email')]
["SrPCNX9d19spppEp4RAk", "5182bbe46832541865000001", "admin@example.com"]
```

## Test 2
1. (Continue from above) `Ctrl`+`F5` Force refresh the browser at http://localhost:3000/#/home
2. Cookies still there.
3. Same console result (pass)

## Test 3
1. (Still continue) Click Users. Now at http://localhost:3000/#/users
2. Cookies still there.
3. Same console result (pass)

## Test 4
1. (Continuing...)  `Ctrl`+`F5` Force refresh the browser at http://localhost:3000/#/users
2. Cookies still there.
3. Same console result (pass)

## Test 5
1. (Continuing...) Click Sign Out
2. Rememberable cookie gone.
3. Console 

```
[BaseApp.Auth.get('authToken'), BaseApp.Auth.get('userId'), BaseApp.Auth.get('user')]
[null, null, null]
```

# urlAuthenticatable off

(all same)

**Comment by joscas** [comment]
Well, you're right, it works. A thorough cleanup of cache + assets solved it. Sorry, should have done this first of all.

**Comment by heartsentwined** [comment]
Glad you found the solution. :+1:

**Comment by kevinansfield** [comment]
In my case I had missed the `autoRecall: true` option somehow. D'oh!

**Comment by heartsentwined** [comment]
Glad it was solved for you too :+1:
